var namespace_d_l_r___data___app_1_1_view_models_1_1_current_project =
[
    [ "EditDataDetailViewModel", "class_d_l_r___data___app_1_1_view_models_1_1_current_project_1_1_edit_data_detail_view_model.html", "class_d_l_r___data___app_1_1_view_models_1_1_current_project_1_1_edit_data_detail_view_model" ],
    [ "EditDataViewModel", "class_d_l_r___data___app_1_1_view_models_1_1_current_project_1_1_edit_data_view_model.html", "class_d_l_r___data___app_1_1_view_models_1_1_current_project_1_1_edit_data_view_model" ],
    [ "ProjectViewModel", "class_d_l_r___data___app_1_1_view_models_1_1_current_project_1_1_project_view_model.html", "class_d_l_r___data___app_1_1_view_models_1_1_current_project_1_1_project_view_model" ]
];