//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLR_Data_App.Localizations {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLR_Data_App.Localizations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The app was developed by the German Aerospace Center (DLR e.V.) in Co-operation with the Friedrich Schiller University Jena and University of Applied Sciences Stralsund. ähnelt.
        /// </summary>
        internal static string about1 {
            get {
                return ResourceManager.GetString("about1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is written in C# and Xamarin and shares the same code on different plattforms. ähnelt.
        /// </summary>
        internal static string about2 {
            get {
                return ResourceManager.GetString("about2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Learn more ähnelt.
        /// </summary>
        internal static string aboutButton {
            get {
                return ResourceManager.GetString("aboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerometer ähnelt.
        /// </summary>
        internal static string accelerometer {
            get {
                return ResourceManager.GetString("accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accept ähnelt.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accuracy ähnelt.
        /// </summary>
        internal static string accuracy {
            get {
                return ResourceManager.GetString("accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Altitude ähnelt.
        /// </summary>
        internal static string altitude {
            get {
                return ResourceManager.GetString("altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your answers were averagely  ähnelt.
        /// </summary>
        internal static string answersCorrectAveragePart1 {
            get {
                return ResourceManager.GetString("answersCorrectAveragePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  correct. ähnelt.
        /// </summary>
        internal static string answersCorrectAveragePart2 {
            get {
                return ResourceManager.GetString("answersCorrectAveragePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully exported into root directory with name dlr_answers_TIMESTAMP. ähnelt.
        /// </summary>
        internal static string answersExportedToRoot {
            get {
                return ResourceManager.GetString("answersExportedToRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next tap will close the app. ähnelt.
        /// </summary>
        internal static string appclosewarning {
            get {
                return ResourceManager.GetString("appclosewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authors ähnelt.
        /// </summary>
        internal static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autologin ähnelt.
        /// </summary>
        internal static string autologin {
            get {
                return ResourceManager.GetString("autologin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Barometer ähnelt.
        /// </summary>
        internal static string barometer {
            get {
                return ResourceManager.GetString("barometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calibration. Please hold the device still ähnelt.
        /// </summary>
        internal static string calibrationpleasehold {
            get {
                return ResourceManager.GetString("calibrationpleasehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compass ähnelt.
        /// </summary>
        internal static string compass {
            get {
                return ResourceManager.GetString("compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please complete your selection to advance. ähnelt.
        /// </summary>
        internal static string completeSelectionToAdvance {
            get {
                return ResourceManager.GetString("completeSelectionToAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entry corrupt ähnelt.
        /// </summary>
        internal static string corruptentry {
            get {
                return ResourceManager.GetString("corruptentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current ähnelt.
        /// </summary>
        internal static string current {
            get {
                return ResourceManager.GetString("current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current profiling ähnelt.
        /// </summary>
        internal static string currentprofiling {
            get {
                return ResourceManager.GetString("currentprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current project ähnelt.
        /// </summary>
        internal static string currentproject {
            get {
                return ResourceManager.GetString("currentproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decline ähnelt.
        /// </summary>
        internal static string decline {
            get {
                return ResourceManager.GetString("decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Degrees ähnelt.
        /// </summary>
        internal static string degrees {
            get {
                return ResourceManager.GetString("degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete saved answers ähnelt.
        /// </summary>
        internal static string deleteSavedAnswersProfiling {
            get {
                return ResourceManager.GetString("deleteSavedAnswersProfiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direction ähnelt.
        /// </summary>
        internal static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driving view ähnelt.
        /// </summary>
        internal static string drivingview {
            get {
                return ResourceManager.GetString("drivingview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Easy: ähnelt.
        /// </summary>
        internal static string easyWithColon {
            get {
                return ResourceManager.GetString("easyWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit data ähnelt.
        /// </summary>
        internal static string editdata {
            get {
                return ResourceManager.GetString("editdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a date and time to select your dataset you want to edit. In the following list all datasets are listed, while the matching dataset to the time is selected. Tip on the dataset of your choise to edit it. ähnelt.
        /// </summary>
        internal static string edithelp {
            get {
                return ResourceManager.GetString("edithelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Evaluation ähnelt.
        /// </summary>
        internal static string evaluation {
            get {
                return ResourceManager.GetString("evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export saved answers ähnelt.
        /// </summary>
        internal static string exportAnswersProfiling {
            get {
                return ResourceManager.GetString("exportAnswersProfiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export database ähnelt.
        /// </summary>
        internal static string exportdatabase {
            get {
                return ResourceManager.GetString("exportdatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully exported into root directory with name Fieldmapp_Database_TIMESTAMP. ähnelt.
        /// </summary>
        internal static string exporttorootwithtimestampsuccessful {
            get {
                return ResourceManager.GetString("exporttorootwithtimestampsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed ähnelt.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select File ähnelt.
        /// </summary>
        internal static string filepicker {
            get {
                return ResourceManager.GetString("filepicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File selected ähnelt.
        /// </summary>
        internal static string fileselected {
            get {
                return ResourceManager.GetString("fileselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File is no Zip Archive ähnelt.
        /// </summary>
        internal static string filetypeerror {
            get {
                return ResourceManager.GetString("filetypeerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        internal static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GPS ähnelt.
        /// </summary>
        internal static string gps {
            get {
                return ResourceManager.GetString("gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gyroscope ähnelt.
        /// </summary>
        internal static string gyroscope {
            get {
                return ResourceManager.GetString("gyroscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hard: ähnelt.
        /// </summary>
        internal static string hardWithColon {
            get {
                return ResourceManager.GetString("hardWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hint ähnelt.
        /// </summary>
        internal static string hint {
            get {
                return ResourceManager.GetString("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you see every available category for this quiz.
        ///Tap on one to answer the questions of it. For each category you see:
        ///- how many questions you have allready answered (left)
        ///- how many questions you need to answer (at least) to finish the category (right) ähnelt.
        /// </summary>
        internal static string hintProfilingListPage {
            get {
                return ResourceManager.GetString("hintProfilingListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hold image to enlarge it ähnelt.
        /// </summary>
        internal static string holdImageToEnlarge {
            get {
                return ResourceManager.GetString("holdImageToEnlarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die True ähnelt.
        /// </summary>
        internal static string introspection0 {
            get {
                return ResourceManager.GetString("introspection0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mostly true ähnelt.
        /// </summary>
        internal static string introspection1 {
            get {
                return ResourceManager.GetString("introspection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Somewhat true ähnelt.
        /// </summary>
        internal static string introspection2 {
            get {
                return ResourceManager.GetString("introspection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mostly not true ähnelt.
        /// </summary>
        internal static string introspection3 {
            get {
                return ResourceManager.GetString("introspection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not true ähnelt.
        /// </summary>
        internal static string introspection4 {
            get {
                return ResourceManager.GetString("introspection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latitude ähnelt.
        /// </summary>
        internal static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licenses ähnelt.
        /// </summary>
        internal static string licenses {
            get {
                return ResourceManager.GetString("licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Longitude ähnelt.
        /// </summary>
        internal static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magnetometer ähnelt.
        /// </summary>
        internal static string magnetometer {
            get {
                return ResourceManager.GetString("magnetometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max ähnelt.
        /// </summary>
        internal static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min ähnelt.
        /// </summary>
        internal static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Moderate: ähnelt.
        /// </summary>
        internal static string moderateWithColon {
            get {
                return ResourceManager.GetString("moderateWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Movement ähnelt.
        /// </summary>
        internal static string movement {
            get {
                return ResourceManager.GetString("movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Account ähnelt.
        /// </summary>
        internal static string newaccount {
            get {
                return ResourceManager.GetString("newaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creating a new profile results in removing the existing profile ähnelt.
        /// </summary>
        internal static string newaccountwarning {
            get {
                return ResourceManager.GetString("newaccountwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New profiling ähnelt.
        /// </summary>
        internal static string newprofiling {
            get {
                return ResourceManager.GetString("newprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Project ähnelt.
        /// </summary>
        internal static string newproject {
            get {
                return ResourceManager.GetString("newproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No active project selected. Please select a project and mark it as active. ähnelt.
        /// </summary>
        internal static string noactiveproject {
            get {
                return ResourceManager.GetString("noactiveproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No author ähnelt.
        /// </summary>
        internal static string noauthor {
            get {
                return ResourceManager.GetString("noauthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No description ähnelt.
        /// </summary>
        internal static string nodescription {
            get {
                return ResourceManager.GetString("nodescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No help available ähnelt.
        /// </summary>
        internal static string nohint {
            get {
                return ResourceManager.GetString("nohint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No title ähnelt.
        /// </summary>
        internal static string notitle {
            get {
                return ResourceManager.GetString("notitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile not found ähnelt.
        /// </summary>
        internal static string nouserfound {
            get {
                return ResourceManager.GetString("nouserfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        internal static string okay {
            get {
                return ResourceManager.GetString("okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orientation sensor ähnelt.
        /// </summary>
        internal static string orientationSensor {
            get {
                return ResourceManager.GetString("orientationSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please complete the profiling. ähnelt.
        /// </summary>
        internal static string pleaseCompleteProfiling {
            get {
                return ResourceManager.GetString("pleaseCompleteProfiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please make a selection ähnelt.
        /// </summary>
        internal static string pleaseMakeSelection {
            get {
                return ResourceManager.GetString("pleaseMakeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please save your answers before closing this page ähnelt.
        /// </summary>
        internal static string pleaseSaveBeforeQuiting {
            get {
                return ResourceManager.GetString("pleaseSaveBeforeQuiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pressure ähnelt.
        /// </summary>
        internal static string pressure {
            get {
                return ResourceManager.GetString("pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy policy ähnelt.
        /// </summary>
        internal static string privacypolicy {
            get {
                return ResourceManager.GetString("privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DLR takes the protection of personal data very seriously. We want you to know when we store data, which types of data are stored and how it is used. As an incorporated entity under German civil law, we are subject to the provisions of the EU General Data Protection Regulation (GDPR), the Federal Data Protection Act (BDSG) and the Telemedia Act (TMG). We have taken technical and organisational measures to ensure our compliance and the compliance of external service providers with the data protection regulati [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string privacytext1 {
            get {
                return ResourceManager.GetString("privacytext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account ähnelt.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiles ähnelt.
        /// </summary>
        internal static string profiles {
            get {
                return ResourceManager.GetString("profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiling ähnelt.
        /// </summary>
        internal static string profiling {
            get {
                return ResourceManager.GetString("profiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiling details ähnelt.
        /// </summary>
        internal static string profilingdetails {
            get {
                return ResourceManager.GetString("profilingdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are missing the profiling module {0} required for this project. ähnelt.
        /// </summary>
        internal static string profilingModuleMissing {
            get {
                return ResourceManager.GetString("profilingModuleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you can see your results in the different difficulties ähnelt.
        /// </summary>
        internal static string profilingResultsDifferentDifficulties {
            get {
                return ResourceManager.GetString("profilingResultsDifferentDifficulties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Details ähnelt.
        /// </summary>
        internal static string projectdetails {
            get {
                return ResourceManager.GetString("projectdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        /// </summary>
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project was launched successfully. ähnelt.
        /// </summary>
        internal static string projectSuccessfullyAdded {
            get {
                return ResourceManager.GetString("projectSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question {0}/{1} Id {2} ähnelt.
        /// </summary>
        internal static string questionEntryFormat {
            get {
                return ResourceManager.GetString("questionEntryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        /// </summary>
        internal static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember login ähnelt.
        /// </summary>
        internal static string rememberlogin {
            get {
                return ResourceManager.GetString("rememberlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Account ähnelt.
        /// </summary>
        internal static string removeaccount {
            get {
                return ResourceManager.GetString("removeaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removing profile from database failed. You will return to the login page. ähnelt.
        /// </summary>
        internal static string removeaccountfailure {
            get {
                return ResourceManager.GetString("removeaccountfailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove your profile and collected data? ähnelt.
        /// </summary>
        internal static string removeaccountwarning {
            get {
                return ResourceManager.GetString("removeaccountwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Database ähnelt.
        /// </summary>
        internal static string removedatabase {
            get {
                return ResourceManager.GetString("removedatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove the database? ähnelt.
        /// </summary>
        internal static string removedatabasewarning {
            get {
                return ResourceManager.GetString("removedatabasewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove profiling ähnelt.
        /// </summary>
        internal static string removeprofiling {
            get {
                return ResourceManager.GetString("removeprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove the profiling? ähnelt.
        /// </summary>
        internal static string removeprofilingwarning {
            get {
                return ResourceManager.GetString("removeprofilingwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove project ähnelt.
        /// </summary>
        internal static string removeproject {
            get {
                return ResourceManager.GetString("removeproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove the project? ähnelt.
        /// </summary>
        internal static string removeprojectwarning {
            get {
                return ResourceManager.GetString("removeprojectwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Results ähnelt.
        /// </summary>
        internal static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saved data ähnelt.
        /// </summary>
        internal static string saveddata {
            get {
                return ResourceManager.GetString("saveddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select date ähnelt.
        /// </summary>
        internal static string selectdate {
            get {
                return ResourceManager.GetString("selectdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your selected date lies in the future and is thus invalid. ähnelt.
        /// </summary>
        internal static string selectedDateIsInFuture {
            get {
                return ResourceManager.GetString("selectedDateIsInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Form ähnelt.
        /// </summary>
        internal static string selectform {
            get {
                return ResourceManager.GetString("selectform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is your selection correct? ähnelt.
        /// </summary>
        internal static string selectionCorrectQuestion {
            get {
                return ResourceManager.GetString("selectionCorrectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select time ähnelt.
        /// </summary>
        internal static string selecttime {
            get {
                return ResourceManager.GetString("selecttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensors ähnelt.
        /// </summary>
        internal static string sensors {
            get {
                return ResourceManager.GetString("sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor Test ähnelt.
        /// </summary>
        internal static string sensortest {
            get {
                return ResourceManager.GetString("sensortest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set as current profiling ähnelt.
        /// </summary>
        internal static string setascurrentprofiling {
            get {
                return ResourceManager.GetString("setascurrentprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set as current project ähnelt.
        /// </summary>
        internal static string setascurrentproject {
            get {
                return ResourceManager.GetString("setascurrentproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign in ähnelt.
        /// </summary>
        internal static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skip ähnelt.
        /// </summary>
        internal static string skip {
            get {
                return ResourceManager.GetString("skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successful ähnelt.
        /// </summary>
        internal static string successful {
            get {
                return ResourceManager.GetString("successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tap for more information ähnelt.
        /// </summary>
        internal static string tapForMorInfo {
            get {
                return ResourceManager.GetString("tapForMorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tap on a bar for more informations ähnelt.
        /// </summary>
        internal static string tapOnBarForInfo {
            get {
                return ResourceManager.GetString("tapOnBarForInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to save changes on profile. ähnelt.
        /// </summary>
        internal static string updateaccountfailure {
            get {
                return ResourceManager.GetString("updateaccountfailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User already exists ähnelt.
        /// </summary>
        internal static string useralreadyexists {
            get {
                return ResourceManager.GetString("useralreadyexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voice recognition ähnelt.
        /// </summary>
        internal static string voicerecognition {
            get {
                return ResourceManager.GetString("voicerecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong entry ähnelt.
        /// </summary>
        internal static string wrongentry {
            get {
                return ResourceManager.GetString("wrongentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Zip Archive ähnelt.
        /// </summary>
        internal static string zippicker {
            get {
                return ResourceManager.GetString("zippicker", resourceCulture);
            }
        }
    }
}
