//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlrDataApp.Modules.OdkProjects.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OdkProjectsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OdkProjectsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DlrDataApp.Modules.OdkProjects.Shared.Localization.OdkProjectsResources", typeof(OdkProjectsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project.
        /// </summary>
        internal static string currentproject {
            get {
                return ResourceManager.GetString("currentproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string newproject {
            get {
                return ResourceManager.GetString("newproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active project selected. Please select a project and mark it as active..
        /// </summary>
        internal static string noactiveproject {
            get {
                return ResourceManager.GetString("noactiveproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        internal static string projectdetails {
            get {
                return ResourceManager.GetString("projectdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project was launched successfully..
        /// </summary>
        internal static string projectSuccessfullyAdded {
            get {
                return ResourceManager.GetString("projectSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove project.
        /// </summary>
        internal static string removeproject {
            get {
                return ResourceManager.GetString("removeproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the project?.
        /// </summary>
        internal static string removeprojectwarning {
            get {
                return ResourceManager.GetString("removeprojectwarning", resourceCulture);
            }
        }
    }
}
