//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlrDataApp.Modules.Profiling.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfilingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfilingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DlrDataApp.Modules.Profiling.Shared.Localization.ProfilingResources", typeof(ProfilingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answers were on average .
        /// </summary>
        internal static string answersCorrectAveragePart1 {
            get {
                return ResourceManager.GetString("answersCorrectAveragePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  correct..
        /// </summary>
        internal static string answersCorrectAveragePart2 {
            get {
                return ResourceManager.GetString("answersCorrectAveragePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete your selection to advance..
        /// </summary>
        internal static string completeSelectionToAdvance {
            get {
                return ResourceManager.GetString("completeSelectionToAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current profiling.
        /// </summary>
        internal static string currentprofiling {
            get {
                return ResourceManager.GetString("currentprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete saved answers.
        /// </summary>
        internal static string deleteSavedAnswersProfiling {
            get {
                return ResourceManager.GetString("deleteSavedAnswersProfiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy:.
        /// </summary>
        internal static string easyWithColon {
            get {
                return ResourceManager.GetString("easyWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        internal static string evaluation {
            get {
                return ResourceManager.GetString("evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export saved answers.
        /// </summary>
        internal static string exportAnswersProfiling {
            get {
                return ResourceManager.GetString("exportAnswersProfiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard:.
        /// </summary>
        internal static string hardWithColon {
            get {
                return ResourceManager.GetString("hardWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string hint {
            get {
                return ResourceManager.GetString("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you see every available category for this quiz.
        ///Tap on one to answer the questions of it. For each category you see:
        ///- how many questions you have allready answered (left)
        ///- how many questions you need to answer (at least) to finish the category (right).
        /// </summary>
        internal static string hintProfilingListPage {
            get {
                return ResourceManager.GetString("hintProfilingListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string introspection0 {
            get {
                return ResourceManager.GetString("introspection0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostly true.
        /// </summary>
        internal static string introspection1 {
            get {
                return ResourceManager.GetString("introspection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somewhat true.
        /// </summary>
        internal static string introspection2 {
            get {
                return ResourceManager.GetString("introspection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostly not true.
        /// </summary>
        internal static string introspection3 {
            get {
                return ResourceManager.GetString("introspection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not true.
        /// </summary>
        internal static string introspection4 {
            get {
                return ResourceManager.GetString("introspection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate:.
        /// </summary>
        internal static string moderateWithColon {
            get {
                return ResourceManager.GetString("moderateWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profiling.
        /// </summary>
        internal static string newprofiling {
            get {
                return ResourceManager.GetString("newprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling.
        /// </summary>
        internal static string profiling {
            get {
                return ResourceManager.GetString("profiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see your results in the different difficulties.
        /// </summary>
        internal static string profilingResultsDifferentDifficulties {
            get {
                return ResourceManager.GetString("profilingResultsDifferentDifficulties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling was launched successfully..
        /// </summary>
        internal static string profilingSuccessfullyAdded {
            get {
                return ResourceManager.GetString("profilingSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question {0}/{1} Id {2}.
        /// </summary>
        internal static string questionEntryFormat {
            get {
                return ResourceManager.GetString("questionEntryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove profiling.
        /// </summary>
        internal static string removeprofiling {
            get {
                return ResourceManager.GetString("removeprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the profiling?.
        /// </summary>
        internal static string removeprofilingwarning {
            get {
                return ResourceManager.GetString("removeprofilingwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your selection correct?.
        /// </summary>
        internal static string selectionCorrectQuestion {
            get {
                return ResourceManager.GetString("selectionCorrectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as current profiling.
        /// </summary>
        internal static string setascurrentprofiling {
            get {
                return ResourceManager.GetString("setascurrentprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap for more information.
        /// </summary>
        internal static string tapForMorInfo {
            get {
                return ResourceManager.GetString("tapForMorInfo", resourceCulture);
            }
        }
    }
}
