//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlrDataApp.Modules.Profiling.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfilingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfilingResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DlrDataApp.Modules.Profiling.Shared.Localization.ProfilingResources", typeof(ProfilingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your answers were on average  ähnelt.
        /// </summary>
        internal static string answersCorrectAveragePart1 {
            get {
                return ResourceManager.GetString("answersCorrectAveragePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  correct. ähnelt.
        /// </summary>
        internal static string answersCorrectAveragePart2 {
            get {
                return ResourceManager.GetString("answersCorrectAveragePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please complete your selection to advance. ähnelt.
        /// </summary>
        internal static string completeSelectionToAdvance {
            get {
                return ResourceManager.GetString("completeSelectionToAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current profiling ähnelt.
        /// </summary>
        internal static string currentprofiling {
            get {
                return ResourceManager.GetString("currentprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete saved answers ähnelt.
        /// </summary>
        internal static string deleteSavedAnswersProfiling {
            get {
                return ResourceManager.GetString("deleteSavedAnswersProfiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Easy: ähnelt.
        /// </summary>
        internal static string easyWithColon {
            get {
                return ResourceManager.GetString("easyWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Evaluation ähnelt.
        /// </summary>
        internal static string evaluation {
            get {
                return ResourceManager.GetString("evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export saved answers ähnelt.
        /// </summary>
        internal static string exportAnswersProfiling {
            get {
                return ResourceManager.GetString("exportAnswersProfiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hard: ähnelt.
        /// </summary>
        internal static string hardWithColon {
            get {
                return ResourceManager.GetString("hardWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hint ähnelt.
        /// </summary>
        internal static string hint {
            get {
                return ResourceManager.GetString("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you see every available category for this quiz.
        ///Tap on one to answer the questions of it. For each category you see:
        ///- how many questions you have allready answered (left)
        ///- how many questions you need to answer (at least) to finish the category (right) ähnelt.
        /// </summary>
        internal static string hintProfilingListPage {
            get {
                return ResourceManager.GetString("hintProfilingListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die True ähnelt.
        /// </summary>
        internal static string introspection0 {
            get {
                return ResourceManager.GetString("introspection0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mostly true ähnelt.
        /// </summary>
        internal static string introspection1 {
            get {
                return ResourceManager.GetString("introspection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Somewhat true ähnelt.
        /// </summary>
        internal static string introspection2 {
            get {
                return ResourceManager.GetString("introspection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mostly not true ähnelt.
        /// </summary>
        internal static string introspection3 {
            get {
                return ResourceManager.GetString("introspection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not true ähnelt.
        /// </summary>
        internal static string introspection4 {
            get {
                return ResourceManager.GetString("introspection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Moderate: ähnelt.
        /// </summary>
        internal static string moderateWithColon {
            get {
                return ResourceManager.GetString("moderateWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New profiling ähnelt.
        /// </summary>
        internal static string newprofiling {
            get {
                return ResourceManager.GetString("newprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please complete the profiling. ähnelt.
        /// </summary>
        internal static string pleaseCompleteProfiling {
            get {
                return ResourceManager.GetString("pleaseCompleteProfiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiling ähnelt.
        /// </summary>
        internal static string profiling {
            get {
                return ResourceManager.GetString("profiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you can see your results in the different difficulties ähnelt.
        /// </summary>
        internal static string profilingResultsDifferentDifficulties {
            get {
                return ResourceManager.GetString("profilingResultsDifferentDifficulties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project was launched successfully. ähnelt.
        /// </summary>
        internal static string projectSuccessfullyAdded {
            get {
                return ResourceManager.GetString("projectSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question {0}/{1} Id {2} ähnelt.
        /// </summary>
        internal static string questionEntryFormat {
            get {
                return ResourceManager.GetString("questionEntryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove profiling ähnelt.
        /// </summary>
        internal static string removeprofiling {
            get {
                return ResourceManager.GetString("removeprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove the profiling? ähnelt.
        /// </summary>
        internal static string removeprofilingwarning {
            get {
                return ResourceManager.GetString("removeprofilingwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is your selection correct? ähnelt.
        /// </summary>
        internal static string selectionCorrectQuestion {
            get {
                return ResourceManager.GetString("selectionCorrectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set as current profiling ähnelt.
        /// </summary>
        internal static string setascurrentprofiling {
            get {
                return ResourceManager.GetString("setascurrentprofiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tap for more information ähnelt.
        /// </summary>
        internal static string tapForMorInfo {
            get {
                return ResourceManager.GetString("tapForMorInfo", resourceCulture);
            }
        }
    }
}
