//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlrDataApp.Modules.Base.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DlrDataApp.Modules.Base.Shared.Localization.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The app was developed by the German Aerospace Center (DLR e.V.) in Co-operation with the Friedrich Schiller University Jena and University of Applied Sciences Stralsund. ähnelt.
        /// </summary>
        public static string about1 {
            get {
                return ResourceManager.GetString("about1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is written in C# and Xamarin and shares the same code on different plattforms. ähnelt.
        /// </summary>
        public static string about2 {
            get {
                return ResourceManager.GetString("about2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Learn more ähnelt.
        /// </summary>
        public static string aboutButton {
            get {
                return ResourceManager.GetString("aboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerometer ähnelt.
        /// </summary>
        public static string accelerometer {
            get {
                return ResourceManager.GetString("accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accept ähnelt.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accuracy ähnelt.
        /// </summary>
        public static string accuracy {
            get {
                return ResourceManager.GetString("accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Altitude ähnelt.
        /// </summary>
        public static string altitude {
            get {
                return ResourceManager.GetString("altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully exported into root directory with name dlr_answers_TIMESTAMP. ähnelt.
        /// </summary>
        public static string answersExportedToRoot {
            get {
                return ResourceManager.GetString("answersExportedToRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next tap will close the app. ähnelt.
        /// </summary>
        public static string appclosewarning {
            get {
                return ResourceManager.GetString("appclosewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authors ähnelt.
        /// </summary>
        public static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autologin ähnelt.
        /// </summary>
        public static string autologin {
            get {
                return ResourceManager.GetString("autologin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Barometer ähnelt.
        /// </summary>
        public static string barometer {
            get {
                return ResourceManager.GetString("barometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calibration. Please hold the device still ähnelt.
        /// </summary>
        public static string calibrationpleasehold {
            get {
                return ResourceManager.GetString("calibrationpleasehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compass ähnelt.
        /// </summary>
        public static string compass {
            get {
                return ResourceManager.GetString("compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entry corrupt ähnelt.
        /// </summary>
        public static string corruptentry {
            get {
                return ResourceManager.GetString("corruptentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current ähnelt.
        /// </summary>
        public static string current {
            get {
                return ResourceManager.GetString("current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decline ähnelt.
        /// </summary>
        public static string decline {
            get {
                return ResourceManager.GetString("decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Degrees ähnelt.
        /// </summary>
        public static string degrees {
            get {
                return ResourceManager.GetString("degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direction ähnelt.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driving view ähnelt.
        /// </summary>
        public static string drivingview {
            get {
                return ResourceManager.GetString("drivingview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driving View Easy ähnelt.
        /// </summary>
        public static string drivingvieweasy {
            get {
                return ResourceManager.GetString("drivingvieweasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driving View Hard ähnelt.
        /// </summary>
        public static string drivingviewhard {
            get {
                return ResourceManager.GetString("drivingviewhard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit data ähnelt.
        /// </summary>
        public static string editdata {
            get {
                return ResourceManager.GetString("editdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a date and time to select your dataset you want to edit. In the following list all datasets are listed, while the matching dataset to the time is selected. Tip on the dataset of your choise to edit it. ähnelt.
        /// </summary>
        public static string edithelp {
            get {
                return ResourceManager.GetString("edithelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export database ähnelt.
        /// </summary>
        public static string exportdatabase {
            get {
                return ResourceManager.GetString("exportdatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully exported into root directory with name Fieldmapp_Database_TIMESTAMP. ähnelt.
        /// </summary>
        public static string exporttorootwithtimestampsuccessful {
            get {
                return ResourceManager.GetString("exporttorootwithtimestampsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed ähnelt.
        /// </summary>
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select File ähnelt.
        /// </summary>
        public static string filepicker {
            get {
                return ResourceManager.GetString("filepicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File selected ähnelt.
        /// </summary>
        public static string fileselected {
            get {
                return ResourceManager.GetString("fileselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File is not of correct type. ähnelt.
        /// </summary>
        public static string filetypeerror {
            get {
                return ResourceManager.GetString("filetypeerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GPS ähnelt.
        /// </summary>
        public static string gps {
            get {
                return ResourceManager.GetString("gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gyroscope ähnelt.
        /// </summary>
        public static string gyroscope {
            get {
                return ResourceManager.GetString("gyroscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hold image to enlarge it ähnelt.
        /// </summary>
        public static string holdImageToEnlarge {
            get {
                return ResourceManager.GetString("holdImageToEnlarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latitude ähnelt.
        /// </summary>
        public static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licenses ähnelt.
        /// </summary>
        public static string licenses {
            get {
                return ResourceManager.GetString("licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Longitude ähnelt.
        /// </summary>
        public static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magnetometer ähnelt.
        /// </summary>
        public static string magnetometer {
            get {
                return ResourceManager.GetString("magnetometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max ähnelt.
        /// </summary>
        public static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min ähnelt.
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Movement ähnelt.
        /// </summary>
        public static string movement {
            get {
                return ResourceManager.GetString("movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Account ähnelt.
        /// </summary>
        public static string newaccount {
            get {
                return ResourceManager.GetString("newaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creating a new profile will delete the existing profile ähnelt.
        /// </summary>
        public static string newaccountwarning {
            get {
                return ResourceManager.GetString("newaccountwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No author ähnelt.
        /// </summary>
        public static string noauthor {
            get {
                return ResourceManager.GetString("noauthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No description ähnelt.
        /// </summary>
        public static string nodescription {
            get {
                return ResourceManager.GetString("nodescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No help available ähnelt.
        /// </summary>
        public static string nohint {
            get {
                return ResourceManager.GetString("nohint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No title ähnelt.
        /// </summary>
        public static string notitle {
            get {
                return ResourceManager.GetString("notitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile not found ähnelt.
        /// </summary>
        public static string nouserfound {
            get {
                return ResourceManager.GetString("nouserfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        public static string okay {
            get {
                return ResourceManager.GetString("okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orientation sensor ähnelt.
        /// </summary>
        public static string orientationSensor {
            get {
                return ResourceManager.GetString("orientationSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please make a selection ähnelt.
        /// </summary>
        public static string pleaseMakeSelection {
            get {
                return ResourceManager.GetString("pleaseMakeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please save your answers before closing this page ähnelt.
        /// </summary>
        public static string pleaseSaveBeforeQuiting {
            get {
                return ResourceManager.GetString("pleaseSaveBeforeQuiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pressure ähnelt.
        /// </summary>
        public static string pressure {
            get {
                return ResourceManager.GetString("pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy policy ähnelt.
        /// </summary>
        public static string privacypolicy {
            get {
                return ResourceManager.GetString("privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DLR takes the protection of personal data very seriously. We want you to know when we store data, which types of data are stored and how it is used. As an incorporated entity under German civil law, we are subject to the provisions of the EU General Data Protection Regulation (GDPR), the Federal Data Protection Act (BDSG) and the Telemedia Act (TMG). We have taken technical and organisational measures to ensure our compliance and the compliance of external service providers with the data protection regulati [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string privacytext1 {
            get {
                return ResourceManager.GetString("privacytext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account ähnelt.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiles ähnelt.
        /// </summary>
        public static string profiles {
            get {
                return ResourceManager.GetString("profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiling details ähnelt.
        /// </summary>
        public static string profilingdetails {
            get {
                return ResourceManager.GetString("profilingdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are missing the profiling module {0} required for this project. ähnelt.
        /// </summary>
        public static string profilingModuleMissing {
            get {
                return ResourceManager.GetString("profilingModuleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        /// </summary>
        public static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember login ähnelt.
        /// </summary>
        public static string rememberlogin {
            get {
                return ResourceManager.GetString("rememberlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Account ähnelt.
        /// </summary>
        public static string removeaccount {
            get {
                return ResourceManager.GetString("removeaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removing profile from database failed. You will return to the login page. ähnelt.
        /// </summary>
        public static string removeaccountfailure {
            get {
                return ResourceManager.GetString("removeaccountfailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove your profile and collected data? ähnelt.
        /// </summary>
        public static string removeaccountwarning {
            get {
                return ResourceManager.GetString("removeaccountwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Database ähnelt.
        /// </summary>
        public static string removedatabase {
            get {
                return ResourceManager.GetString("removedatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove the database? ähnelt.
        /// </summary>
        public static string removedatabasewarning {
            get {
                return ResourceManager.GetString("removedatabasewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Results ähnelt.
        /// </summary>
        public static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saved data ähnelt.
        /// </summary>
        public static string saveddata {
            get {
                return ResourceManager.GetString("saveddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select date ähnelt.
        /// </summary>
        public static string selectdate {
            get {
                return ResourceManager.GetString("selectdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your selected date lies in the future and is thus invalid. ähnelt.
        /// </summary>
        public static string selectedDateIsInFuture {
            get {
                return ResourceManager.GetString("selectedDateIsInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Form ähnelt.
        /// </summary>
        public static string selectform {
            get {
                return ResourceManager.GetString("selectform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select time ähnelt.
        /// </summary>
        public static string selecttime {
            get {
                return ResourceManager.GetString("selecttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensors ähnelt.
        /// </summary>
        public static string sensors {
            get {
                return ResourceManager.GetString("sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor Test ähnelt.
        /// </summary>
        public static string sensortest {
            get {
                return ResourceManager.GetString("sensortest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set as current project ähnelt.
        /// </summary>
        public static string setascurrentproject {
            get {
                return ResourceManager.GetString("setascurrentproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign in ähnelt.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skip ähnelt.
        /// </summary>
        public static string skip {
            get {
                return ResourceManager.GetString("skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successful ähnelt.
        /// </summary>
        public static string successful {
            get {
                return ResourceManager.GetString("successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tap on a bar for more informations ähnelt.
        /// </summary>
        public static string tapOnBarForInfo {
            get {
                return ResourceManager.GetString("tapOnBarForInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to save changes on profile. ähnelt.
        /// </summary>
        public static string updateaccountfailure {
            get {
                return ResourceManager.GetString("updateaccountfailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User already exists ähnelt.
        /// </summary>
        public static string useralreadyexists {
            get {
                return ResourceManager.GetString("useralreadyexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voice recognition ähnelt.
        /// </summary>
        public static string voicerecognition {
            get {
                return ResourceManager.GetString("voicerecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong entry ähnelt.
        /// </summary>
        public static string wrongentry {
            get {
                return ResourceManager.GetString("wrongentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Zip Archive ähnelt.
        /// </summary>
        public static string zippicker {
            get {
                return ResourceManager.GetString("zippicker", resourceCulture);
            }
        }
    }
}
